FROM alpine:latest
MAINTAINER cjrollo (Christopher Rollo)

# Update System
RUN apk upgrade && rm -rf /var/cache/apk/*

# Set the environment

# Install apps
# Create Userspace

# Get to it...
CMD [/bin/ash]
